<table class="table">
    <thead>
    <tr>
        <th>{{__('product.col')}}</th>
        <th>{{__('product.col2')}}</th>
        <th>{{__('product.col3')}}</th>
        <th>{{__('product.col4')}}</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>XS</td>
        <td>84</td>
        <td>62</td>
        <td>92</td>
    </tr>
    <tr>
        <td>S</td>
        <td>88</td>
        <td>66</td>
        <td>96</td>
    </tr>
    <tr>
        <td>M</td>
        <td>92</td>
        <td>70</td>
        <td>100</td>
    </tr>
    <tr>
        <td>L</td>
        <td>96</td>
        <td>74</td>
        <td>104</td>
    </tr>
    </tbody>
</table>
